### ISSUE TITLE
Deployment failed on aws app runner

### ISSUE THREAD

**Issue by hamza0786** [DarkMakerofc/tiktok-downloader-api#2]
Hi i am always getting this when i deploy it in on aws app runner:

10-15-2024 11:15:58 AM [AppRunner] Successfully pulled your application source code.
10-15-2024 11:15:58 AM [AppRunner] Successfully validate configuration file.
10-15-2024 11:15:59 AM [AppRunner] Starting source code build.
10-15-2024 11:16:58 AM [AppRunner] Successfully built your application source code.
10-15-2024 11:17:08 AM [AppRunner] Provisioning instances and deploying image for publicly accessible service.
10-15-2024 11:17:18 AM [AppRunner] Performing health check on protocol `TCP` [Port: '8080'].
10-15-2024 11:23:29 AM [AppRunner] Health check failed on protocol `TCP` [Port: '8080']. Check your configured port number. For more information, see the application logs.
10-15-2024 11:23:42 AM [AppRunner] Deployment with ID : 7970be59927f41f4871025f69d699a1c failed. Failure reason : Health check failed.

**Comment by hamza0786** [comment]
no need issue fixed and working...

**Comment by DarkMakerofc** [comment]
> no need issue fixed and working...

I'm happy It's about working
